# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  create:
    tags:
      - '*'
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      checks: write
      pull-requests: write
      contents: write

    steps:
    - name: '📄 Checkout'
      uses: actions/checkout@v4
      
    - name: '🔨 Use Node.js 20.x'
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
        cache: 'npm'
        
    - name: '🔨 Install node packages'
      run: npm ci
    - name: Install node package for custom task
      run: npm ci
      working-directory: src/SpotCheckV0
      
    - name: '🔨 Build'
      run: npm run build
      
    - name: '✅ Test'
      uses: ArtiomTr/jest-coverage-report-action@v2
      with:
        test-script: npm test
        skip-step: install

    - name: 🔖 Set VERSION variable from tag
      id: version
      if: startsWith(github.ref, 'refs/tags/')
      run: | 
        TAG=${{ github.ref_name }}
        echo "VERSION=${TAG#v}" >> $GITHUB_ENV
        
    - name: '📦 Package'
      if: steps.version.outcome == 'success'
      run: npm run package-extension -- --env version=$VERSION
        
    - name: '🚀 Create release'
      if: steps.version.outcome == 'success'
      run: gh release create v$VERSION --generate-notes
      env:
        GITHUB_TOKEN: ${{ github.TOKEN }}
    
    - name: '🚀 Upload release files'
      if: steps.version.outcome == 'success'
      run: gh release upload v$VERSION igorkalders.spotcheck-$VERSION.vsix
      env:
        GITHUB_TOKEN: ${{ github.TOKEN }}
    
    - name: '📦 Publish package'
      if: steps.version.outcome == 'success'
      run: npm run publish-extension -- --vsix igorkalders.spotcheck-$VERSION.vsix --auth-type pat -t ${{secrets.PUBLISH_PAT}}
